version: '3.9'
services:
  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: YourStrongPassword
    ports:
      - "1433:1433"
    networks:
      - mynetwork

  api:
    build:
      context: .
      dockerfile: Ecommerce.API/Dockerfile

    ports:
      - "7174:80"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=EcommerceDB;User=sa;Password=YourStrongPassword;
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123456
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx

    volumes:
      - ~/.aspnet/https:/https

    depends_on:
      - db
    networks:
      - mynetwork

networks:
  mynetwork:
